In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

In [ ]:
2+3

In [ ]:
6/3

In [ ]:
x=1:10
x
mean(x)
median(x)
var(x)
sd(x)

In [ ]:
# cat and print ,both can be used for printing
cat(x)
cat('Mean of x is:',mean(x))
cat('Median of x is :',median(x))
cat('Variance of x is:',var(x))
cat('Standard Deviation of x is:',sd(x))


In [ ]:
#To print in next line use \n
cat(x,'\n')
cat('Mean of x is:',mean(x),'\n')
cat('Median of x is :',median(x),'\n')
cat('Variance of x is:',var(x),'\n')
cat('Standard Deviation of x is:',sd(x),'\n')

In [ ]:
print(x)
print(paste('Mean of x is:',mean(x)))
print(paste('Median of x is :',median(x)))
print(paste('Variance of x is:',var(x)))
print(paste('Standard Deviation of x is:',sd(x)))


In [ ]:
x=8+7
x

In [ ]:
#Creation of character value
x="dataset"
x
class(x)
typeof(x)
length(x)
attributes(x)

In [ ]:
#Creation of numerical variable
x=23
x
class(x)
typeof(x)
length(x)
attributes(x)

In [ ]:
#Craetion of integer VAriable
x=23L
x
class(x)
typeof(x)
length(x)
attributes(x)

In [ ]:
#Creation of complex variable
x=2+3i
x
class(x)
typeof(x)
length(x)
attributes(x)

In [ ]:
#Creation of logical variable
x=TRUE
x
class(x)
typeof(x)
length(x)
attributes(x)

In [ ]:
#An Empty logical vector
vector()

In [20]:
#A vector of mode character with 5 elements
vector("character",length=5)

[1] "" "" "" "" ""

In [21]:
#Same but usinbg the constructor directly
character(5)

[1] "" "" "" "" ""

In [22]:
#A numeric vector with 5 elements
numeric(5)

[1] 0 0 0 0 0

In [23]:
#A logical vector with 5 elements
logical(5)

[1] FALSE FALSE FALSE FALSE FALSE

In [25]:
#Numeric vector having 5 elements
x=c(12,23,34,45,56)

In [26]:
x
class(x)

[1] 12 23 34 45 56

[1] "numeric"

In [27]:
#Integer having 5 elements
x=c(12L,23L,34L,45L,56L)
x
class(x)
length(x)

[1] 12 23 34 45 56

[1] "integer"

[1] 5

In [29]:
#Logical vector having 5 vectors
y=c(TRUE,TRUE,FALSE,TRUE,FALSE)
y
class(y)
length(y)

[1]  TRUE  TRUE FALSE  TRUE FALSE

[1] "logical"

[1] 5

In [30]:
#character vector having3 elements
z=c("HELLO","TO","TIRED")
z
class(z)
length(z)

[1] "HELLO" "TO"    "TIRED"

[1] "character"

[1] 3

In [31]:
#Adding element at the end
print("Elements in Z before")
z
z=c(z,"SORRY")
print("Elemenyts in z after adding new elements")
z

[1] "Elements in Z before"


[1] "HELLO" "TO"    "TIRED"

[1] "Elemenyts in z after adding new elements"


[1] "HELLO" "TO"    "TIRED" "SORRY"

In [32]:
#Add element at the front
print("Elements in Z before")
z
z=c("HEY",z)
print("Elemenyts in z after adding new elements")
z

[1] "Elements in Z before"


[1] "HELLO" "TO"    "TIRED" "SORRY"

[1] "Elemenyts in z after adding new elements"


[1] "HEY"   "HELLO" "TO"    "TIRED" "SORRY"

In [33]:
#Vector from a sequence of numbers
a=1:10
a

[1]  1  2  3  4  5  6  7  8  9 10

In [34]:
seq(10)

[1]  1  2  3  4  5  6  7  8  9 10

In [35]:
seq(1,10,by=0.1)

[1]  1.0  1.1  1.2  1.3  1.4  1.5  1.6  1.7  1.8  1.9  2.0  2.1  2.2  2.3  2.4
[16]  2.5  2.6  2.7  2.8  2.9  3.0  3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9
[31]  4.0  4.1  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.0  5.1  5.2  5.3  5.4
[46]  5.5  5.6  5.7  5.8  5.9  6.0  6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9
[61]  7.0  7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.0  8.1  8.2  8.3  8.4
[76]  8.5  8.6  8.7  8.8  8.9  9.0  9.1  9.2  9.3  9.4  9.5  9.6  9.7  9.8  9.9
[91] 10.0

In [36]:
#Special values
1/0

[1] Inf

In [37]:
0/0

[1] NaN

In [39]:
#e raised to the power of infinity is infinity
exp(Inf)
#e raised to the power of negative infinity is zero
exp(-Inf)

[1] Inf

[1] 0

In [40]:
Inf-Inf

[1] NaN

In [41]:
log(0)
log(1)

[1] -Inf

[1] 0

In [42]:
#Mixing types in a vector
a=c(1.7,"a")
a

[1] "1.7" "a"

In [43]:
b=c(TRUE,2,3,FALSE)#TRUE value is converted to 1 and FALSE to 0
b

[1] 1 2 3 0

In [44]:
c=c("a",TRUE)
c

[1] "a"    "TRUE"

In [45]:
#EXPLICIT TYPE CONVERSION
as.numeric("1")#conversion from character to numeric

[1] 1

In [46]:
as.numeric(c("49","66"))

[1] 49 66

In [47]:
as.numeric(c("49","66","six"))#Invalid conversion ,Missing values will be introduced

Warning message in eval(expr, envir, enclos):
“NAs introduced by coercion”

[1] 49 66 NA

In [49]:
as.character(22)#Conversion from numeric to chracter
as.character(c(22,23,24))#Conversion from numeric to character

[1] "22"

[1] "22" "23" "24"

In [50]:
#MATRIX
m=matrix(nrow=2,ncol=2)
m

[,1] [,2]
[1,] NA   NA  
[2,] NA   NA

In [51]:
dim(m)
class(m)
typeof(m)

[1] 2 2

[1] "matrix"

[1] "logical"

In [52]:
m=matrix(c(1:3))
print("Given matrix is")
print(m)
print("Dimensions of given matrix")
print(dim(m))
print("Class of given matrix is:")
print(class(m))
print("Type of given matrix is:")
print(typeof(m))

[1] "Given matrix is"
     [,1]
[1,]    1
[2,]    2
[3,]    3
[1] "Dimensions of given matrix"
[1] 3 1
[1] "Class of given matrix is:"
[1] "matrix"
[1] "Type of given matrix is:"
[1] "integer"


In [54]:
a=matrix(1:6,nrow=2,ncol=3)
print(a)

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6


In [55]:
m=1:10
print(m)
print(dim(m))
dim(m)=c(2,5)
print(m)
print(dim(m))

 [1]  1  2  3  4  5  6  7  8  9 10
NULL
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10
[1] 2 5


In [57]:
name=readline(prompt="Enter name:")
age=readline(prompt="Enter age:")
age=as.integer(age)
print(paste("HI,",name,"next year you will be",age+1,"years old"))

Enter name:Rishab
Enter age:15
[1] "HI, Rishab next year you will be 16 years old"


In [59]:
w=readline()
w


Hello


[1] "Hello"